apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: json-server
  name: json-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: json-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: json-server
    spec:
      containers:
      - image: docker.io/clue/json-server:latest
        name: json-server
        ports:
        - containerPort: 80
        resources: {}
