apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-app
  name: gitops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-app
  strategy: {}
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
      - image: docker.io/nginx
        name: ""
        ports:
        - containerPort: ""
