apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-app
  name: gitops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-app
  strategy: {}
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
      - image: adtrdr/json-server-app:v0.1.0-beta.3
        name: json-server
      - image: adtrdr/json-server-app:latest
        imagePullPolicy: Always
        name: json-server-app
        ports:
        - containerPort: 8080
