---
apiVersion: v1
kind: Service
metadata:
  name: gitops-service
  labels:
    app: gitops-svc    
spec:
  clusterIP: None
  ports:
  - name: 8000-8000
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: gitops-app
  type: ClusterIP
