# https://github.com/drdkadtr/gh-action-argocd-app-env/settings/actions/runners
name: self-hosted

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # https://github.com/actions/runner
  self-hosted-run:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Setup infra
        run: |
          .github/self-hosted/setup.sh

      - name: Setup argocd and patch it
        run: |
          .github/self-hosted/argo.sh

      - name: Port forward argcd UI
        run: |
          killall kubectl || kubectl port-forward svc/argocd-server 8080:443 -n argocd &

      - name: Wait for cluster to finish bootstraping
        run: kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=300s

      - name: Print Arcd setup
        id: argo-setup
        run: |
          echo "::set-output name=URL::'http://localhost:8080'"
          echo "::set-output name=LOGIN::'admin'"
          echo "::set-output name=PASSWORD::$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d)"
