# https://github.com/drdkadtr/gh-action-argocd-app-env/settings/actions/runners
name: self-hosted

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # https://github.com/actions/runner
  my-self-hosted-run:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Setup infra
        if: github.event_name == 'workflow_dispatch'
        run: |
          ./infra/setup.sh

      - name: Setup argocd and patch it
        if: github.event_name == 'workflow_dispatch'
        run: |
          ./infra/argo.sh

      - name: Setup argcd application
        if: github.event_name == 'workflow_dispatch'
        run: |
          kubectl apply -f application.yaml

      - name: Port forward argcd UI
        if: github.event_name == 'workflow_dispatch'
        run: |
          killall kubectl || kubectl port-forward svc/argocd-server 8080:443 -n argocd &

      - name: Print arcd url
        if: github.event_name == 'workflow_dispatch'
        run: echo "http://localhost:8080"
