name: self-hosted

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # https://github.com/actions/runner
  my-self-hosted-run:

    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - run: echo "::set-env name=DAY_OF_WEEK::$( date +%a )"

      - name: Setup infra
        if: github.event_name == 'workflow_dispatch'
        run: |
          ./infra/setup.sh

      - name: Setup argocd
        if: github.event_name == 'workflow_dispatch'
        run: |
          ./infra/argo.sh

      - name: Setup argcd application
        if: github.event_name == 'workflow_dispatch'
        run: |
          kubectl apply -f application.yaml
